import Head from 'next/head'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MAE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NavBar/>
        <h1>MAE Client Platform. </h1>
      </div>
    </div>
  )
}
